\documentclass[11pt,spanish,a4paper,]{article}
\usepackage{lmodern}
%\usepackage[spanish]{babel} %walter
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\PassOptionsToPackage{hyphens}{url} % url is loaded by hyperref
\usepackage[unicode=true]{hyperref}
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
\hypersetup{
            pdftitle={P1 - Uso de Smartphones y Riesgo de Adiccion},
            colorlinks=true,
            linkcolor=blue,
            citecolor=Blue,
            urlcolor=Blue,
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{geometry}
\geometry{a4paper, centering, text={16cm,25cm}}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,main=spanish]{babel}
\else
  \usepackage{polyglossia}
  \setmainlanguage[]{}
\fi
\usepackage[style=authoryear-comp,]{biblatex}
\addbibresource{references.bib}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\usepackage{longtable,booktabs}
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{long table}}{}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{P1 - Uso de Smartphones y Riesgo de Adiccion}

%% MONASH STUFF

%% CAPTIONS
\RequirePackage{caption}
\DeclareCaptionStyle{italic}[justification=centering]
 {labelfont={bf},textfont={it},labelsep=colon}
\captionsetup[figure]{style=italic,format=hang,singlelinecheck=true}
\captionsetup[table]{style=italic,format=hang,singlelinecheck=true}
%% FONT
\usepackage{bera}
\usepackage[charter,expert]{mathdesign}
\usepackage[lf,t]{FiraSans}
\usepackage[scale=0.9]{sourcecodepro}
\RequirePackage{fontawesome}

%% HEADERS AND FOOTERS
\RequirePackage{fancyhdr}
\pagestyle{fancy}
\rfoot{\Large\sffamily\raisebox{-0.1cm}{\textbf{\thepage}}}
\makeatletter
\lhead{\textsf{\expandafter{\@title}}}
\makeatother
\rhead{}
\cfoot{}
\setlength{\headheight}{15pt}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}
\fancypagestyle{plain}{%
\fancyhf{} % clear all header and footer fields
\fancyfoot[C]{\sffamily\thepage} % except the center
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}}

%% MATHS
\RequirePackage{bm,amsmath}
\allowdisplaybreaks

%% GRAPHICS
\RequirePackage{graphicx}
\setcounter{topnumber}{2}
\setcounter{bottomnumber}{2}
\setcounter{totalnumber}{4}
\renewcommand{\topfraction}{0.85}
\renewcommand{\bottomfraction}{0.85}
\renewcommand{\textfraction}{0.15}
\renewcommand{\floatpagefraction}{0.8}

%% SECTION TITLES
\RequirePackage[compact,sf,bf]{titlesec}
\titleformat*{\section}{\Large\sf\bfseries\color[rgb]{0.0, 0.7451, 0.8745}}
\titleformat*{\subsection}{\large\sf\bfseries\color[rgb]{0.0, 0, 0}}
\titleformat*{\subsubsection}{\sf\bfseries\color[rgb]{0,0,0}}
\titlespacing{\section}{0pt}{2ex}{.5ex}
\titlespacing{\subsection}{0pt}{1.5ex}{0ex}
\titlespacing{\subsubsection}{0pt}{.5ex}{0ex}


%% TITLE PAGE
\def\Date{\number\day}
\def\Month{\ifcase\month\or
 de Enero del\or de Febrero del\or de Marzo del\or de Abril del\or de Mayo del\or de Junio del\or
de Julio del\or de Agosto del\or de Septiembre del\or de Octubre del\or de Noviembre del\or de Diciembre del\fi}
\def\Year{\number\year}

%% LINE AND PAGE BREAKING
\sloppy
\clubpenalty = 10000
\widowpenalty = 10000
\brokenpenalty = 10000
\RequirePackage{microtype}

%% PARAGRAPH BREAKS
\setlength{\parskip}{1.4ex}
\setlength{\parindent}{0em}

%% HYPERLINKS
\RequirePackage{xcolor} % Needed for links
\definecolor{darkblue}{rgb}{0,0,.6}
\RequirePackage{url}

\makeatletter
\@ifpackageloaded{hyperref}{}{\RequirePackage{hyperref}}
\makeatother
\hypersetup{
     citecolor=0 0 0,
     breaklinks=true,
     bookmarksopen=true,
     bookmarksnumbered=true,
     linkcolor=darkblue,
     urlcolor=blue,
     citecolor=darkblue,
     colorlinks=true}

\usepackage[showonlyrefs]{mathtools}
\usepackage[no-weekday]{eukdate}

%% BIBLIOGRAPHY

\makeatletter
\@ifpackageloaded{biblatex}{}{\usepackage[style=authoryear-comp, backend=biber, natbib=true]{biblatex}}
\makeatother
\ExecuteBibliographyOptions{bibencoding=utf8,minnames=1,maxnames=3, maxbibnames=99,dashed=false,terseinits=true,giveninits=true,uniquename=false,uniquelist=false,doi=false, isbn=false,url=true,sortcites=false}

\DeclareFieldFormat{url}{\texttt{\url{#1}}}
\DeclareFieldFormat[article]{pages}{#1}
\DeclareFieldFormat[inproceedings]{pages}{\lowercase{pp.}#1}
\DeclareFieldFormat[incollection]{pages}{\lowercase{pp.}#1}
\DeclareFieldFormat[article]{volume}{\mkbibbold{#1}}
\DeclareFieldFormat[article]{number}{\mkbibparens{#1}}
\DeclareFieldFormat[article]{title}{\MakeCapital{#1}}
\DeclareFieldFormat[article]{url}{}
%\DeclareFieldFormat[book]{url}{}
%\DeclareFieldFormat[inbook]{url}{}
%\DeclareFieldFormat[incollection]{url}{}
%\DeclareFieldFormat[inproceedings]{url}{}
\DeclareFieldFormat[inproceedings]{title}{#1}
\DeclareFieldFormat{shorthandwidth}{#1}
%\DeclareFieldFormat{extrayear}{}
% No dot before number of articles
\usepackage{xpatch}
\xpatchbibmacro{volume+number+eid}{\setunit*{\adddot}}{}{}{}
% Remove In: for an article.
\renewbibmacro{in:}{%
  \ifentrytype{article}{}{%
  \printtext{\bibstring{in}\intitlepunct}}}

\AtEveryBibitem{\clearfield{month}}
\AtEveryCitekey{\clearfield{month}}

\makeatletter
\DeclareDelimFormat[cbx@textcite]{nameyeardelim}{\addspace}
\makeatother

\author{\sf{\Large\textbf{Hiter Frank Rubio
Peralta}\\\large Alumno\\[0.5cm]}{\Large\textbf{Jossep Jorge Froilan
Choroco Neyra}\\\large Alumno\\[0.5cm]}{\Large\textbf{Joel David De la
Cruz Cardenas}\\\large Alumno\\[0.5cm]}{\Large\textbf{Rodrigo Octavio
Lucatoni Flores Ruiz}\\\large Alumno\\[0.5cm]}{\Large\textbf{Victor
Andres Diaz Garcia}\\\large Alumno\\[0.5cm]}}

\date{Invalid Date}
\makeatletter
%\lfoot{\sf Rubio Peralta, Neyra, Cardenas, Ruiz, Garcia: \@date}
\makeatother


%%%% PAGE STYLE FOR FRONT PAGE OF REPORTS

\makeatletter
\def\organization#1{\gdef\@organization{#1}}
\def\telephone#1{\gdef\@telephone{#1}}
\def\email#1{\gdef\@email{#1}}
\makeatother
  \organization{Introduccion a Ciencia de Datos e Inteligencia
Artificial}

  \def\name{CIENCIA DE DATOS E \newline INTELIGENCIA ARTIFICIAL}

  \telephone{+51 936 603 314}

  \email{pandascore@gmail.com}

%\def\webaddress{\url{http://buseco.monash.edu/ebs/consulting/}}
%\def\abn{12 377 614 012}
\def\extraspace{\vspace*{1.1cm}}
\makeatletter
\def\contactdetails{\faicon{phone} & \@telephone \\
                    \faicon{envelope} & \@email}
\makeatother

\usepackage[absolute,overlay]{textpos}
\setlength{\TPHorizModule}{1cm}
\setlength{\TPVertModule}{1cm}

%%%% FRONT PAGE OF REPORTS

\def\reporttype{Curso:} %walter

\long\def\front#1#2#3{
\newpage
\begin{textblock}{7}(12.7,28.2)\hfill
%\includegraphics[height=0.6cm]{_extensions/numbats/report/AACSB}~~~
%\includegraphics[height=0.6cm]{_extensions/numbats/report/EQUIS}~~~
%\includegraphics[height=0.6cm]{_extensions/numbats/report/AMBA}
\end{textblock}
\begin{singlespacing}
\thispagestyle{empty}
\vspace*{-1.4cm}
\hspace*{-1.4cm}
\hbox to 16cm{
  \hbox to 6.5cm{\vbox to 14cm{\vbox to 25cm{
    \includegraphics[width=5.4cm]{_extensions/numbats/report/logo}
    \vfill
%    \includegraphics[width=2cm]{_extensions/numbats/report/MBSportrait}
    \vspace{0.4cm}
    \par
    \parbox{6.3cm}{\raggedright
      \sf\color[rgb]{0.0, 0.7451, 0.8745}
      {\large\textbf{\name}}\par
      \vspace{.7cm}
      \tabcolsep=0.12cm\sf\small
      \begin{tabular}{@{}ll@{}}\contactdetails
      \end{tabular}
      \vspace*{0.3cm}\par
%      ABN: \abn\par
    }
  }\vss}\hss}
  \hspace*{0.2cm}
  \hbox to 1cm{\vbox to 14cm{\rule{1pt}{26.8cm}\vss}\hss\hfill}
  \hbox to 10cm{\vbox to 14cm{\vbox to 25cm{
      \vspace*{3cm}\sf\raggedright
      \parbox{10cm}{\sf\raggedright\baselineskip=1.2cm
         \fontsize{24.88}{30}\color[rgb]{0.0, 0.7451, 0.8745}\sf\textbf{#1}}
      \par
      \vfill
      \large
      \vbox{\parskip=0.8cm #2}\par
      \vspace*{2cm}\par
      \reporttype\\[0.3cm]
      \hbox{#3}%\\[2cm]\
      \vspace*{1cm}
      {\large\sf\textbf{\Date~\Month~\Year}}
   }\vss}
  }}
\end{singlespacing}
\newpage
}

\makeatletter
\def\titlepage{\front{\expandafter{\@title}}{\@author}{\@organization}}
\makeatother

\usepackage{setspace}
\setstretch{1.25}

\newcounter{none}
\usepackage{array}
\usepackage{calc}
\usepackage{float}
\floatplacement{table}{H}
\floatplacement{figure}{H}
\usepackage{colortbl}
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
\usepackage{etoolbox}
\AtBeginEnvironment{Shaded}{\setstretch{1.1}}
\fvset{breaklines=true}
\usepackage{csquotes}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Tabla de contenidos}
\else
  \newcommand\contentsname{Tabla de contenidos}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{Listado de Figuras}
\else
  \newcommand\listfigurename{Listado de Figuras}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{Listado de Tablas}
\else
  \newcommand\listtablename{Listado de Tablas}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figura}
\else
  \newcommand\figurename{Figura}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Tabla}
\else
  \newcommand\tablename{Tabla}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listado}
\newcommand*\listoflistings{\listof{codelisting}{Listado de Listados}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother


\begin{document}
\titlepage

{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{2}
\tableofcontents
}
\listoftables
\listoffigures
\providecommand{\pandocbounded}[1]{#1}

\newpage

\section{Resumen}\label{resumen}

\emph{Instrucciones para esta sección: este resumen se escribe
\textbf{al final}, cuando ya se tengan los resultados de la exploración
de datos y las conclusiones de P1. Debe tener entre 150 y 200 palabras e
incluir, en este orden: (1) qué dataset se usó y cuántos
registros/columnas tiene, (2) el objetivo del análisis (qué se busca
entender sobre \texttt{etiqueta\_de\_adiccion}), (3) las dos o tres
decisiones de limpieza más importantes que se tomaron y por qué, (4) los
dos o tres hallazgos más relevantes del EDA, citando cifras reales
obtenidas del código (no inventadas ni copiadas de un borrador), y (5)
una frase que conecte con lo que se hará en la P2. No copiar texto de
otras secciones; debe ser una síntesis propia, escrita por el equipo.}

\section{Planteamiento del problema}\label{planteamiento-del-problema}

El uso intensivo de celulares puede influir en la salud integral de las
personas al relacionarse con irregularidades en el sueño, estrés,
dificultades en el ámbito académico y laboral. Además, la investigación
requiere de una conceptualización alta: una alta frecuencia de uso no
significa necesariamente a una condición clínica. Articulos como SABAS
permiten estudiar síntomas de uso problemático, pero no sustituyen una
evaluación profesional \textcite{Csibi2018}. La literatura también ayuda
con asociaciones entre el uso del smartphone y el desempeño académico,
aunque con limitaciones claras para atribuir causalidad
\textcite{AmezBaert2020}.

Para este proyecto, se formula la siguiente pregunta de análisis:

\begin{quote}
¿Qué patrones de uso, descanso y contexto personal están asociados con
la etiqueta de adicción en el conjunto de datos
smartphone-use-prediction?
\end{quote}

\section{Contexto del dataset}\label{contexto-del-dataset}

\subsection{Fuente y unidad de
análisis}\label{fuente-y-unidad-de-anuxe1lisis}

El archivo
\texttt{Smartphone\_Usage\_And\_Addiction\_Analysis\_7500\_Rows.csv} fue
proporcionado para el proyecto y corresponde al dataset publicado como
\emph{Smartphone Usage and Addiction Analysis} en Kaggle
\textcite{KaggleDataset}. Cada fila representa a un usuario y contiene
indicadores demográficos, de comportamiento digital, descanso, estrés e
impacto percibido en actividades académicas o laborales.

La unidad de análisis es el usuario. El dataset incluye 7,500 registros
y 16 columnas originales: dos identificadores, nueve variables
numéricas, cuatro variables categóricas y la etiqueta binaria objetivo.

\subsection{Diccionario de variables}\label{diccionario-de-variables}

\begin{itemize}
\tightlist
\item
  \textbf{Identificadores:} \texttt{ID\_transaccion} y
  \texttt{ID\_usuario} son variables de texto. Se usan para verificar
  unicidad, pero no aportan significado analítico y se excluirán como
  predictores.
\item
  \textbf{Demografía:} \texttt{edad} (numérica) y \texttt{genero}
  (categórica) caracterizan la muestra.
\item
  \textbf{Uso del smartphone:} \texttt{horas\_diarias\_pantalla},
  \texttt{horas\_redes\_sociales}, \texttt{horas\_videojuegos},
  \texttt{horas\_trabajo/estudio}, \texttt{notificaciones\_por\_dia},
  \texttt{aperturas\_apps\_por\_dia} y \texttt{tiempo\_pantalla\_finde}
  son variables numéricas que miden intensidad y tipo de uso.
\item
  \textbf{Bienestar y contexto:} \texttt{horas\_sueño} es numérica;
  \texttt{nivel\_estres} y \texttt{impacto\_academico/laboral} son
  categóricas. Se emplean para explorar descanso e impacto funcional.
\item
  \textbf{Severidad:} \texttt{nivel\_adiccion} es categórica ordinal. Se
  describe en P1, pero se excluye como predictor en P2 por fuga de
  información.
\item
  \textbf{Objetivo:} \texttt{etiqueta\_de\_adiccion} es binaria: 0
  significa \emph{No adicción} y 1 significa \emph{Con adicción}.
\end{itemize}

La variable \texttt{nivel\_adiccion} contiene una categorización de
severidad (\texttt{None}, \texttt{Mild}, \texttt{Moderate},
\texttt{Severe}). Por su definición operativa, puede estar construida
directamente a partir de la etiqueta final; por ello se audita
explícitamente antes de considerar su uso en P2.

\section{Carga y exploración
inicial}\label{carga-y-exploraciuxf3n-inicial}

\subsection{Librerías}\label{libreruxedas}

El primer bloque reúne las librerías necesarias para el proyecto y el
estilo de seaborn

\protect\phantomsection\label{setup}
\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ======================================================================}
\CommentTok{\# CONFIGURACIÓN ÚNICA DEL REPORTE}
\CommentTok{\# Librerías y estilos se ejecutan una sola vez}
\CommentTok{\# ======================================================================}
\ImportTok{import}\NormalTok{ pandas }\ImportTok{as}\NormalTok{ pd}
\ImportTok{import}\NormalTok{ numpy }\ImportTok{as}\NormalTok{ np}
\ImportTok{from}\NormalTok{ matplotlib.pyplot }\ImportTok{import}\NormalTok{ boxplot}
\ImportTok{from}\NormalTok{ matplotlib.pyplot }\ImportTok{import}\NormalTok{ hist}
\ImportTok{import}\NormalTok{ matplotlib.pyplot }\ImportTok{as}\NormalTok{ plt}
\ImportTok{import}\NormalTok{ seaborn }\ImportTok{as}\NormalTok{ sns}
\ImportTok{from}\NormalTok{ IPython.display }\ImportTok{import}\NormalTok{ display, Latex}
\ImportTok{import}\NormalTok{ kagglehub}
\ImportTok{from}\NormalTok{ scipy }\ImportTok{import}\NormalTok{ stats}

\NormalTok{sns.set\_theme(style}\OperatorTok{=}\StringTok{"whitegrid"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

El segundo bloque, que no se imprime en el PDF para no alargarlo, define
funciones de presentación: la función \texttt{tabla()}, que reproduce
desde Python el estilo de tabla (\texttt{kable} con \emph{booktabs}), en
el PDF se omite el código que solo dibuja los gráficos, igual que en la
plantilla del curso; todo ese código está completo y comentado en
\texttt{Project-Report.qmd}. Sí se muestra todo el código que carga,
transforma o calcula.

\subsection{Carga de datos}\label{carga-de-datos}

Usando la librería de kaggle y os logramos una carga universal exitosa
en cualquier equipo y evitamos errores de carga del dataset

\protect\phantomsection\label{carga}
\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cargamos el archivo csv}
\NormalTok{path }\OperatorTok{=}\NormalTok{ (kagglehub.dataset\_download }
\NormalTok{       (}\StringTok{"jayjoshi37/smartphone{-}usage{-}and{-}addiction{-}prediction"}\NormalTok{))}

\ImportTok{import}\NormalTok{ os}
\CommentTok{\# Ruta directa al archivo CSV combinando la ruta de descarga y el nombre del}
\CommentTok{\# archivo}
\NormalTok{ruta\_csv }\OperatorTok{=}\NormalTok{ (os.path.join(path, }
           \StringTok{"Smartphone\_Usage\_And\_Addiction\_Analysis\_7500\_Rows.csv"}\NormalTok{))}
\NormalTok{df }\OperatorTok{=}\NormalTok{ pd.read\_csv(ruta\_csv)}
\NormalTok{n\_filas, n\_columnas }\OperatorTok{=}\NormalTok{ df.shape}
\BuiltInTok{print}\NormalTok{(}\SpecialStringTok{f"Dimensiones: }\SpecialCharTok{\{}\NormalTok{n\_filas}\SpecialCharTok{:,\}}\SpecialStringTok{ filas x }\SpecialCharTok{\{}\NormalTok{n\_columnas}\SpecialCharTok{\}}\SpecialStringTok{ columnas"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Dimensiones: 7,500 filas x 16 columnas
\end{verbatim}

El archivo se carga completo, con 7500 filas y 16 columnas. \texttt{df}
no se modifica en ningún momento: todas las transformaciones posteriores
se aplican sobre copias, de modo que cada decisión puede contrastarse
contra el archivo original.

\subsection{Dimensiones y estructura}\label{dimensiones-y-estructura}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primeras }\OperatorTok{=}\NormalTok{ df.head(}\DecValTok{5}\NormalTok{).fillna(}\StringTok{"NaN"}\NormalTok{).T.astype(}\BuiltInTok{str}\NormalTok{)}
\NormalTok{primeras.columns }\OperatorTok{=}\NormalTok{ [}\SpecialStringTok{f"Usuario }\SpecialCharTok{\{}\NormalTok{i}\SpecialCharTok{\}}\SpecialStringTok{"} \ControlFlowTok{for}\NormalTok{ i }\KeywordTok{in} \BuiltInTok{range}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{6}\NormalTok{)]}
\NormalTok{primeras.index.name }\OperatorTok{=} \StringTok{"Columna"}
\NormalTok{tabla(primeras, tamanio}\OperatorTok{=}\StringTok{"footnotesize"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tbl-primeras-filas}Primeras cinco filas del archivo
original, transpuestas: cada fila de la tabla es una columna del CSV.}

\centering{

\begingroup\footnotesize\setstretch{1.15}
\begin{tabular}{llllll}
\toprule
\textbf{Columna} & \textbf{Usuario 1} & \textbf{Usuario 2} & \textbf{Usuario 3} & \textbf{Usuario 4} & \textbf{Usuario 5} \\
\midrule
transaction\_id & TXN00001 & TXN00002 & TXN00003 & TXN00004 & TXN00005 \\
user\_id & U00001 & U00002 & U00003 & U00004 & U00005 \\
age & 21 & 24 & 31 & 32 & 25 \\
gender & Male & Other & Other & Other & Male \\
daily\_screen\_time\_hours & 3.23 & 5.09 & 6.06 & 7.83 & 9.96 \\
social\_media\_hours & 2.01 & 3.81 & 1.36 & 5.85 & 5.92 \\
gaming\_hours & 0.89 & 2.24 & 3.83 & 1.51 & 3.42 \\
work\_study\_hours & 4.55 & 4.44 & 2.35 & 3.54 & 5.27 \\
sleep\_hours & 7.55 & 7.66 & 4.92 & 8.23 & 6.21 \\
notifications\_per\_day & 248 & 127 & 44 & 178 & 136 \\
app\_opens\_per\_day & 154 & 71 & 106 & 107 & 177 \\
weekend\_screen\_time & 3.95 & 6.71 & 8.68 & 9.77 & 12.55 \\
stress\_level & Medium & Medium & High & High & Low \\
academic\_work\_impact & Yes & Yes & No & Yes & No \\
addiction\_level & NaN & NaN & Mild & Moderate & Severe \\
addicted\_label & 0 & 0 & 0 & 1 & 1 \\
\bottomrule
\end{tabular}
\endgroup

}

\end{table}%

La Tabla~\ref{tbl-primeras-filas} se presenta transpuesta porque las 16
columnas no caben a lo ancho de la página. Ya en estas cinco filas
aparece una señal de alerta: los usuarios 1 y 2 muestran \texttt{NaN}
(valor nulo) en \texttt{addiction\_level}, un valor que se investiga en
la sección (Sección~\ref{sec-val-nul}).

\begin{table}

\caption{\label{tbl-estructura}Estructura del archivo: tipo de dato
asignado por pandas, valores no nulos, nulos y valores distintos por
columna.}

\centering{

\begingroup\small\setstretch{1.15}
\begin{tabular}{llccc}
\toprule
\textbf{Columna} & \textbf{Tipo (pandas)} & \textbf{No nulos} & \textbf{Nulos} & \textbf{Valores distintos} \\
\midrule
transaction\_id & str & 7,500 & 0 & 7,500 \\
user\_id & str & 7,500 & 0 & 7,500 \\
age & int64 & 7,500 & 0 & 18 \\
gender & str & 7,500 & 0 & 3 \\
daily\_screen\_time\_hours & float64 & 7,500 & 0 & 900 \\
social\_media\_hours & float64 & 7,500 & 0 & 551 \\
gaming\_hours & float64 & 7,500 & 0 & 401 \\
work\_study\_hours & float64 & 7,500 & 0 & 551 \\
sleep\_hours & float64 & 7,500 & 0 & 451 \\
notifications\_per\_day & int64 & 7,500 & 0 & 231 \\
app\_opens\_per\_day & int64 & 7,500 & 0 & 166 \\
weekend\_screen\_time & float64 & 7,500 & 0 & 1,096 \\
stress\_level & str & 7,500 & 0 & 3 \\
academic\_work\_impact & str & 7,500 & 0 & 2 \\
addiction\_level & str & 6,681 & 819 & 3 \\
addicted\_label & int64 & 7,500 & 0 & 2 \\
\bottomrule
\end{tabular}
\endgroup

}

\end{table}%

\textbf{Interpretación.} La Tabla~\ref{tbl-estructura} permite verificar
que el tipo asignado por pandas sea coherente con lo que representa cada
variable:

\begin{itemize}
\tightlist
\item
  Las nueve variables de uso, edad y sueño se cargaron como números
  (\texttt{int64} o \texttt{float64}) y no como texto, que es el error
  silencioso más frecuente al leer un CSV.
\item
  \texttt{addicted\_label} se cargó como entero, pero es una variable
  \textbf{categórica binaria}: el tipo de dato no coincide con su
  naturaleza estadística, y así se tratará en el análisis.
\item
  Las columnas de texto (tipo \texttt{object} en pandas 2 o \texttt{str}
  en pandas 3) son de dos clases muy distintas: \texttt{transaction\_id}
  y \texttt{user\_id} tienen 7500 valores distintos, uno por fila, lo
  que las identifica como \textbf{identificadores}; en cambio,
  \texttt{gender}, \texttt{stress\_level},
  \texttt{academic\_work\_impact} y \texttt{addiction\_level} tienen
  entre 2 y 4 valores, es decir, son \textbf{categóricas}.
\item
  Solo \texttt{addiction\_level} presenta nulos np.int64(819), y muestra
  3 valores distintos, cuando una escala de severidad suele tener cuatro
  niveles.
\end{itemize}

\subsection{Tipos de variables y primeras
estadísticas}\label{tipos-de-variables-y-primeras-estaduxedsticas}

\begin{table}

\caption{\label{tbl-diccionario}Diccionario de variables: nombre
original, nombre usado en el reporte, tipo estadístico y descripción.}

\centering{

\begingroup\scriptsize\setstretch{1.1}
\begin{tabular}{llp{2.7cm}>{\raggedright\arraybackslash}p{4.2cm}}
\toprule
\textbf{Columna original} & \textbf{Nombre en el reporte} & \textbf{Tipo estadístico} & \textbf{Descripción} \\
\midrule
transaction\_id & ID\_transaccion & Identificador & Código del registro (TXN00001...) \\
user\_id & ID\_usuario & Identificador & Código del usuario (U00001...) \\
age & edad & Cuantitativa discreta & Edad en años cumplidos \\
gender & genero & Cualitativa nominal & Masculino, Femenino u Otro \\
daily\_screen\_time\_hours & horas\_diarias\_pantalla & Cuantitativa continua & Horas de pantalla en un día típico \\
social\_media\_hours & horas\_redes\_sociales & Cuantitativa continua & Horas diarias en redes sociales \\
gaming\_hours & horas\_videojuegos & Cuantitativa continua & Horas diarias en videojuegos \\
work\_study\_hours & horas\_trabajo/estudio & Cuantitativa continua & Horas diarias de trabajo o estudio \\
sleep\_hours & horas\_sueño & Cuantitativa continua & Horas de sueño por noche \\
notifications\_per\_day & notificaciones\_por\_dia & Cuantitativa discreta & Notificaciones recibidas al día \\
app\_opens\_per\_day & aperturas\_apps\_por\_dia & Cuantitativa discreta & Veces que abre aplicaciones al día \\
weekend\_screen\_time & tiempo\_pantalla\_finde & Cuantitativa continua & Horas de pantalla en un día de fin de semana \\
stress\_level & nivel\_estres & Cualitativa ordinal & Bajo < Medio < Alto \\
academic\_work\_impact & impacto\_academico/laboral & Cualitativa nominal (binaria) & Si el uso afecta sus estudios o trabajo (Sí/No) \\
addiction\_level & nivel\_adiccion & Cualitativa ordinal & Ninguna < Leve < Moderada < Severa \\
addicted\_label & etiqueta\_de\_adiccion & Cualitativa binaria (objetivo) & 1 = adicto, 0 = no adicto \\
\bottomrule
\end{tabular}
\endgroup

}

\end{table}%

La Tabla~\ref{tbl-diccionario} resume la naturaleza de cada variable. La
distinción entre tipos estadísticos no es un detalle formal: decide qué
gráficos y estadísticos corresponden a cada variable (histogramas y
boxplots para las cuantitativas, gráficos de barras para las
cualitativas) y, en la P2, cómo se codificará cada una.

\subsection{Calidad de datos}\label{calidad-de-datos}

\protect\phantomsection\label{val-nulos-colum-duplicadas}
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nulos\_por\_columna }\OperatorTok{=}\NormalTok{ df.isnull().}\BuiltInTok{sum}\NormalTok{()}
\NormalTok{filas\_duplicadas }\OperatorTok{=}\NormalTok{ df.duplicated().}\BuiltInTok{sum}\NormalTok{()}
\BuiltInTok{print}\NormalTok{(}\StringTok{"Valores nulos por columna:"}\NormalTok{)}
\BuiltInTok{print}\NormalTok{(nulos\_por\_columna[nulos\_por\_columna }\OperatorTok{\textgreater{}} \DecValTok{0}\NormalTok{])}
\BuiltInTok{print}\NormalTok{(}\SpecialStringTok{f"}\CharTok{\textbackslash{}n}\SpecialStringTok{Filas duplicadas: }\SpecialCharTok{\{}\NormalTok{filas\_duplicadas}\SpecialCharTok{\}}\SpecialStringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Valores nulos por columna:
addiction_level    819
dtype: int64

Filas duplicadas: 0
\end{verbatim}

Se encontraron \textbf{819 valores nulos} en la columna
\texttt{nivel\_adicción}, esto es aproximadamente un 10.92\% de los
registros del dataset. Por otro lado, no hay filas duplicadas,
probablemente esto sea porque los usuarios con
\texttt{nivel\_adiccion\ =\ None} simplemente no completaron esa escala
de severidad. A partir de este problema, decidimos \textbf{excluir} a la
variable \texttt{nivel\_adicción} ya que esta representa una fuga de
información y no aporta información nueva.

\begin{table}

\caption{\label{tbl-describe-num}Primeras estadísticas de las variables
numéricas (archivo original).}

\centering{

\begingroup\small\setstretch{1.15}
\begin{tabular}{p{3.5cm}*{8}{c}}
\toprule
\textbf{Variable} & \textbf{n} & \textbf{Media} & \textbf{Desv. est.} & \textbf{Mín.} & \textbf{Q1} & \textbf{Mediana} & \textbf{Q3} & \textbf{Máx.} \\
\midrule
edad & 7,500 & 26.57 & 5.20 & 18.00 & 22.00 & 27.00 & 31.00 & 35.00 \\
horas\_diarias\_pantalla & 7,500 & 7.50 & 2.61 & 3.00 & 5.22 & 7.53 & 9.81 & 12.00 \\
horas\_redes\_sociales & 7,500 & 3.27 & 1.59 & 0.50 & 1.91 & 3.27 & 4.63 & 6.00 \\
horas\_videojuegos & 7,500 & 2.01 & 1.15 & 0.00 & 1.02 & 2.04 & 2.99 & 4.00 \\
horas\_trabajo/estudio & 7,500 & 3.24 & 1.60 & 0.50 & 1.85 & 3.23 & 4.64 & 6.00 \\
horas\_sueño & 7,500 & 6.74 & 1.28 & 4.50 & 5.63 & 6.72 & 7.84 & 9.00 \\
notificaciones\_por\_dia & 7,500 & 134.26 & 66.59 & 20.00 & 76.00 & 134.00 & 191.00 & 250.00 \\
aperturas\_apps\_por\_dia & 7,500 & 97.83 & 48.42 & 15.00 & 55.00 & 98.00 & 140.00 & 180.00 \\
tiempo\_pantalla\_finde & 7,500 & 9.24 & 2.72 & 3.58 & 6.96 & 9.26 & 11.54 & 14.88 \\
etiqueta\_de\_adiccion & 7,500 & 0.71 & 0.45 & 0.00 & 0.00 & 1.00 & 1.00 & 1.00 \\
\bottomrule
\end{tabular}
\endgroup

}

\end{table}%

Los rangos que se observan en la anterior tabla \texttt{df.describe()}
son coherentes con lo que representan las variables. La edad está entre
18 y 35 años, con una media de 26.57, las horas de pantalla diaria van
de 3 a 12 horas con una media de 7.50, las horas de sueño de 4.5 a 9 con
una media de 6.74 y las horas de trabajo/estudio de 0.5 a 6 con media de
3.24. Por otro lado, los valores de notificaciones por día y aperturas
de apps por día muestran una alta dispersión, eso es esperable ya que
cada usuario tiene distintos patrones de uso que generar cantidades
completamente diferentes de notificaciones y aperturas. Además,
\texttt{ID\_transaccion} y \texttt{ID\_usuario} se conservan únicamente
como referencia para verificar autenticidad, pero no forman parte del
análisis.

\section{Preprocesamiento y decisiones de data
wrangling}\label{preprocesamiento-y-decisiones-de-data-wrangling}

Notamos que hay 819 valores nulos en la clumna ``nivel\_adiccion'', por
lo que procederemos a analizar las filas que contengan valores nulos en
esta columna

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{columnas\_mostrar }\OperatorTok{=}\NormalTok{ [}
    \StringTok{"ID\_transaccion"}\NormalTok{, }\StringTok{"edad"}\NormalTok{, }\StringTok{"genero"}\NormalTok{,}
    \StringTok{"horas\_diarias\_pantalla"}\NormalTok{, }\StringTok{"horas\_sueño"}\NormalTok{,}
    \StringTok{"nivel\_estres"}\NormalTok{, }\StringTok{"etiqueta\_de\_adiccion"}
\NormalTok{]}

\NormalTok{df\_adiccionnull }\OperatorTok{=}\NormalTok{ df\_renombrado[df\_renombrado[}\StringTok{"nivel\_adiccion"}\NormalTok{].isnull()]}
\NormalTok{df\_adiccionnull\_head }\OperatorTok{=}\NormalTok{ df\_adiccionnull.head()}

\NormalTok{tabla(df\_adiccionnull\_head[columnas\_mostrar], indice}\OperatorTok{=}\VariableTok{False}\NormalTok{, tamanio}\OperatorTok{=}\StringTok{"scriptsize"}\NormalTok{, interlineado}\OperatorTok{=}\FloatTok{1.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tbl-nulos-head}Estadisticas de las final con valores
nulos}

\centering{

\begingroup\scriptsize\setstretch{1.1}
\begin{tabular}{lclcclc}
\toprule
\textbf{ID\_transaccion} & \textbf{edad} & \textbf{genero} & \textbf{horas\_diarias\_pantalla} & \textbf{horas\_sueño} & \textbf{nivel\_estres} & \textbf{etiqueta\_de\_adiccion} \\
\midrule
TXN00001 & 21 & Male & 3.23 & 7.55 & Medium & 0 \\
TXN00002 & 24 & Other & 5.09 & 7.66 & Medium & 0 \\
TXN00009 & 21 & Other & 4.38 & 6.23 & High & 0 \\
TXN00012 & 27 & Other & 5.16 & 7.79 & High & 0 \\
TXN00014 & 32 & Male & 4.09 & 5.54 & High & 0 \\
\bottomrule
\end{tabular}
\endgroup

}

\end{table}%

\subsection{Revisión de fuga de información}\label{sec-val-nul}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crosstab }\OperatorTok{=}\NormalTok{ pd.crosstab(df\_renombrado[}\StringTok{"nivel\_adiccion"}\NormalTok{], df\_renombrado[}\StringTok{"etiqueta\_de\_adiccion"}\NormalTok{])}
\NormalTok{tabla(crosstab)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tbl-crosstab-fuga}Tabla cruzada entre nivel\_adiccion y
etiqueta\_de\_adiccion.}

\centering{

\begingroup\small\setstretch{1.15}
\begin{tabular}{lcc}
\toprule
\textbf{nivel\_adiccion} & \textbf{0} & \textbf{1} \\
\midrule
Mild & 1,373 & 0 \\
Moderate & 0 & 2,874 \\
Severe & 0 & 2,434 \\
\bottomrule
\end{tabular}
\endgroup

}

\end{table}%

En la tabla cruzada Notamos que la columna \texttt{nivel\_adiccion} o
cae en 0 cuando es baja o cae en 1 cuando es media o alta, no hay
ninguna excepción para alguien de adicción media p alta, la información
de \texttt{etiqueta\_de\_adiccion} es la necesaria y objetivo para este
análisis puesto que queremos encontrar qué patrones de uso, descanso y
contexto personal están asociados con la etiqueta de adicción en el
conjunto de datos que estamos abordando.

Notamos que la columna \texttt{nivel\_adiccion} \emph{o cae en 0 cuando
es baja} o \emph{cae en 1 cuando es media o alta}, no hay ninguna
excepción para alguien de adicción media p alta, la información de
\texttt{etiqueta\_de\_adiccion} es la necesaria y objetivo para este
análisis puesto que queremos encontrar qué patrones de uso, descanso y
contexto personal están asociados con la etiqueta de adicción en el
conjunto de datos que estamos abordando. Esto permitirá no repetir
información en el proceso de modelamiento, ya que
\texttt{nivel\_adiccion} ya revelaría que
\texttt{etiqueta\_de\_adiccion} es 1 o 0. Por lo tanto, con esto
confirmamos que incluir \texttt{nivel\_adiccion} en el predictor del
modelo P2 sería igual a una \textbf{fuga de información}, entonces lo
excluiremos de las variables predictoras. Además, se descartan
\texttt{ID\_transaccion} e \texttt{ID\_usuario} al ser solo
identificadores sin un valor predictivo.

\textbf{Contrato de nombres para el resto del proyecto} (acordado por el
equipo, para que el código de todos encaje sin romperse al juntarlo): a
partir de aquí se crean y se reutilizan siempre las mismas variables:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\OperatorTok{=}\NormalTok{ df\_renombrado.drop(columns}\OperatorTok{=}\NormalTok{[}\StringTok{"ID\_transaccion"}\NormalTok{, }\StringTok{"ID\_usuario"}\NormalTok{, }\StringTok{"nivel\_adiccion"}\NormalTok{])}
\NormalTok{num\_cols }\OperatorTok{=}\NormalTok{ [}\StringTok{"edad"}\NormalTok{, }\StringTok{"horas\_diarias\_pantalla"}\NormalTok{, }\StringTok{"horas\_redes\_sociales"}\NormalTok{,}
\StringTok{"horas\_videojuegos"}\NormalTok{, }\StringTok{"horas\_trabajo/estudio"}\NormalTok{, }\StringTok{"horas\_sueño"}\NormalTok{, }\StringTok{"notificaciones\_por\_dia"}\NormalTok{,}
\StringTok{"aperturas\_apps\_por\_dia"}\NormalTok{, }\StringTok{"tiempo\_pantalla\_finde"}\NormalTok{]}
\NormalTok{cat\_cols }\OperatorTok{=}\NormalTok{ [}\StringTok{"genero"}\NormalTok{, }\StringTok{"nivel\_estres"}\NormalTok{, }\StringTok{"impacto\_academico/laboral"}\NormalTok{]}
\NormalTok{tabla(df\_clean.head())}
\end{Highlighting}
\end{Shaded}

\protect\phantomsection\label{df-limpio}
\begingroup\small\setstretch{1.15}
\begin{table}
\caption{Primeras cinco filas del dataset limpio (df\_clean).}\tabularnewline

\centering
\begin{tabular}{cclccccccccllc}
\toprule
\textbf{index} & \textbf{edad} & \textbf{genero} & \textbf{horas\_diarias\_pantalla} & \textbf{horas\_redes\_sociales} & \textbf{horas\_videojuegos} & \textbf{horas\_trabajo/estudio} & \textbf{horas\_sueño} & \textbf{notificaciones\_por\_dia} & \textbf{aperturas\_apps\_por\_dia} & \textbf{tiempo\_pantalla\_finde} & \textbf{nivel\_estres} & \textbf{impacto\_academico/laboral} & \textbf{etiqueta\_de\_adiccion} \\
\midrule
0 & 21 & Male & 3.23 & 2.01 & 0.89 & 4.55 & 7.55 & 248 & 154 & 3.95 & Medium & Yes & 0 \\
1 & 24 & Other & 5.09 & 3.81 & 2.24 & 4.44 & 7.66 & 127 & 71 & 6.71 & Medium & Yes & 0 \\
2 & 31 & Other & 6.06 & 1.36 & 3.83 & 2.35 & 4.92 & 44 & 106 & 8.68 & High & No & 0 \\
3 & 32 & Other & 7.83 & 5.85 & 1.51 & 3.54 & 8.23 & 178 & 107 & 9.77 & High & Yes & 1 \\
4 & 25 & Male & 9.96 & 5.92 & 3.42 & 5.27 & 6.21 & 136 & 177 & 12.55 & Low & No & 1 \\
\bottomrule
\end{tabular}
\end{table}

\endgroup

\subsubsection{Enriquecimiento de
datos:}\label{enriquecimiento-de-datos}

Se crean dos variables derivadas para el análisis exploratorio:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean[}\StringTok{"horas\_ocio"}\NormalTok{] }\OperatorTok{=}\NormalTok{ df\_renombrado[}\StringTok{"horas\_redes\_sociales"}\NormalTok{] }\OperatorTok{+}\NormalTok{ df\_renombrado[}\StringTok{"horas\_videojuegos"}\NormalTok{]}
\NormalTok{df\_clean[}\StringTok{"ratio\_finde\_diario"}\NormalTok{] }\OperatorTok{=}\NormalTok{ df\_renombrado[}\StringTok{"tiempo\_pantalla\_finde"}\NormalTok{]}\OperatorTok{/}\NormalTok{df\_renombrado[}\StringTok{"horas\_diarias\_pantalla"}\NormalTok{]}
\NormalTok{df\_clean[}\StringTok{"estado\_adiccion"}\NormalTok{] }\OperatorTok{=}\NormalTok{ df\_clean[}\StringTok{"etiqueta\_de\_adiccion"}\NormalTok{].replace(\{}\DecValTok{1}\NormalTok{:}\StringTok{"Adicto"}\NormalTok{, }\DecValTok{0}\NormalTok{:}\StringTok{"No adicto"}\NormalTok{\})}
\NormalTok{tabla(df\_clean.head())}
\end{Highlighting}
\end{Shaded}

\protect\phantomsection\label{variables-derivadas}
\begingroup\small\setstretch{1.15}
\begin{table}
\caption{Primeras cinco filas del dataset con variables derivadas (horas\_ocio y
ratio\_finde\_diario).}\tabularnewline

\centering
\begin{tabular}{cclccccccccllcccl}
\toprule
\textbf{index} & \textbf{edad} & \textbf{genero} & \textbf{horas\_diarias\_pantalla} & \textbf{horas\_redes\_sociales} & \textbf{horas\_videojuegos} & \textbf{horas\_trabajo/estudio} & \textbf{horas\_sueño} & \textbf{notificaciones\_por\_dia} & \textbf{aperturas\_apps\_por\_dia} & \textbf{tiempo\_pantalla\_finde} & \textbf{nivel\_estres} & \textbf{impacto\_academico/laboral} & \textbf{etiqueta\_de\_adiccion} & \textbf{horas\_ocio} & \textbf{ratio\_finde\_diario} & \textbf{estado\_adiccion} \\
\midrule
0 & 21 & Male & 3.23 & 2.01 & 0.89 & 4.55 & 7.55 & 248 & 154 & 3.95 & Medium & Yes & 0 & 2.90 & 1.22 & No adicto \\
1 & 24 & Other & 5.09 & 3.81 & 2.24 & 4.44 & 7.66 & 127 & 71 & 6.71 & Medium & Yes & 0 & 6.05 & 1.32 & No adicto \\
2 & 31 & Other & 6.06 & 1.36 & 3.83 & 2.35 & 4.92 & 44 & 106 & 8.68 & High & No & 0 & 5.19 & 1.43 & No adicto \\
3 & 32 & Other & 7.83 & 5.85 & 1.51 & 3.54 & 8.23 & 178 & 107 & 9.77 & High & Yes & 1 & 7.36 & 1.25 & Adicto \\
4 & 25 & Male & 9.96 & 5.92 & 3.42 & 5.27 & 6.21 & 136 & 177 & 12.55 & Low & No & 1 & 9.34 & 1.26 & Adicto \\
\bottomrule
\end{tabular}
\end{table}

\endgroup

Con esto se confirma que \texttt{estado\_adiccion} es solo una
traducción de \texttt{etiqueta\_de\_adiccion} a etiquetas legibles: 5308
registros se etiquetaron como ``Adicto'' (equivalente a 1) y 2192 como
``No adicto'' (equivalente a 0). No se está introduciendo nada nuevo.
Las variables \texttt{num\_cols} y \texttt{cat\_cols} actualizadas son:
- \texttt{num\_cols}: edad, horas\_diarias\_pantalla,
horas\_redes\_sociales, horas\_videojuegos, horas\_trabajo/estudio,
horas\_sueño, notificaciones\_por\_dia, aperturas\_apps\_por\_dia,
tiempo\_en\_pantalla\_fin\_de\_semana, horas\_ocio,
ratio\_finde\_diario, etiqueta\_de\_adiccion - \texttt{cat\_cols}:
genero, nivel\_estres, impacto\_academico/laboral, estado\_adiccion

\section{Análisis exploratorio de
datos}\label{anuxe1lisis-exploratorio-de-datos}

\subsection{Análisis univariado}\label{anuxe1lisis-univariado}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{counts }\OperatorTok{=}\NormalTok{ df\_clean[}\StringTok{"estado\_adiccion"}\NormalTok{].value\_counts()}
\NormalTok{counts.plot(kind}\OperatorTok{=}\StringTok{"bar"}\NormalTok{, color}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}darkred\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}darkgreen\textquotesingle{}}\NormalTok{], edgecolor}\OperatorTok{=}\StringTok{"none"}\NormalTok{)}
\NormalTok{plt.xlabel(}\StringTok{"Estado de adicción"}\NormalTok{)}
\NormalTok{plt.ylabel(}\VariableTok{None}\NormalTok{)}
\NormalTok{plt.xticks(rotation}\OperatorTok{=}\DecValTok{0}\NormalTok{)}
\NormalTok{plt.show()}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/fig-estado-adiccion-output-1.pdf}}

}

\caption{\label{fig-estado-adiccion}Distribución de la variable
objetivo: estado de adicción (0 = No adicción, 1 = Con adicción).}

\end{figure}%

De los 7,500 registros, \textbf{5308 (70.77\%)} corresponden a la clase
``Con adicción'' y \textbf{2192 (29.23\%)} a ``No adicción''. Hay un
desbalance, la clase positiva tiene más del doble de registros que la
negativa.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{colores }\OperatorTok{=}\NormalTok{ [}\StringTok{\textquotesingle{}steelblue\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}darkorange\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}forestgreen\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}crimson\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gold\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}lightcoral\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}yellowgreen\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}cadetblue\textquotesingle{}}\NormalTok{,}
\StringTok{\textquotesingle{}powderblue\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}lightgreen\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}lightgray\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}plum\textquotesingle{}}\NormalTok{]}
\NormalTok{contador }\OperatorTok{=} \DecValTok{0}
\ControlFlowTok{for}\NormalTok{ col }\KeywordTok{in}\NormalTok{ num\_cols:}
\NormalTok{    plt.figure(figsize}\OperatorTok{=}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{3}\NormalTok{))}
\NormalTok{    sns.histplot(}
\NormalTok{        data}\OperatorTok{=}\NormalTok{df\_clean,}
\NormalTok{        x}\OperatorTok{=}\NormalTok{col,}
\NormalTok{        bins}\OperatorTok{=}\DecValTok{20}\NormalTok{,}
\NormalTok{        kde}\OperatorTok{=}\VariableTok{False}\NormalTok{,}
\NormalTok{        color}\OperatorTok{=}\NormalTok{ colores[contador]}
\NormalTok{    )}
\NormalTok{    plt.title(}\SpecialStringTok{f"Histograma de }\SpecialCharTok{\{}\NormalTok{col}\SpecialCharTok{\}}\SpecialStringTok{"}\NormalTok{)}
\NormalTok{    plt.xlabel(}\VariableTok{None}\NormalTok{)}
\NormalTok{    plt.ylabel(}\VariableTok{None}\NormalTok{)}
\NormalTok{    plt.tight\_layout() }\CommentTok{\#es una función de matplotlib que ajusta automáticamente los márgenes}
\NormalTok{    plt.show()}
\NormalTok{    contador }\OperatorTok{+=}\DecValTok{1}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-2.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-3.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-4.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-5.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-6.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-7.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-8.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-16-output-9.pdf}}

Cada histograma

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean[}\StringTok{\textquotesingle{}estado\_adiccion\textquotesingle{}}\NormalTok{].value\_counts().plot(kind}\OperatorTok{=}\StringTok{\textquotesingle{}bar\textquotesingle{}}\NormalTok{,color}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}darkred\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}darkgreen\textquotesingle{}}\NormalTok{])}
\NormalTok{plt.show() }\CommentTok{\#usamos la variable comunicativa de \textquotesingle{}etiqueta\_de\_adiccion\textquotesingle{}}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-17-output-1.pdf}}

\emph{El gráfico de barras muestra una clara asimetría y desbalance de
clases, donde la categoría ``Adiccto'' predomina ampliamente (superando
las 5,000 observaciones) frente a la de ``No adicto'' (alrededor de
2,200). Este desequilibrio implica que, para fases posteriores de
modelado o análisis estadístico, se debe considerar el balanceo de datos
o métricas de evaluación adecuadas para evitar sesgos hacia la clase
mayoritaria.}

Los boxplots se apoyan en los cuartiles, que dividen los datos ordenados
en cuatro partes iguales \autocite{walpole2012probabilidad}:

\begin{equation}\protect\phantomsection\label{eq-cuartiles}{
Q_k = \text{valor en la posición } \frac{k}{4}(n+1)
}\end{equation}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{colores }\OperatorTok{=}\NormalTok{ [}\StringTok{\textquotesingle{}steelblue\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}darkorange\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}forestgreen\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}lightcoral\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}yellowgreen\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}cadetblue\textquotesingle{}}\NormalTok{,}
\StringTok{\textquotesingle{}powderblue\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}lightgreen\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}lightgray\textquotesingle{}}\NormalTok{]}
\NormalTok{num\_cols }\OperatorTok{=}\NormalTok{ [}
    \StringTok{"edad"}\NormalTok{,}
    \StringTok{"horas\_diarias\_pantalla"}\NormalTok{,}
    \StringTok{"horas\_redes\_sociales"}\NormalTok{,}
    \StringTok{"horas\_videojuegos"}\NormalTok{,}
    \StringTok{"horas\_trabajo/estudio"}\NormalTok{,}
    \StringTok{"horas\_sueño"}\NormalTok{,}
    \StringTok{"notificaciones\_por\_dia"}\NormalTok{,}
    \StringTok{"aperturas\_apps\_por\_dia"}\NormalTok{,}
    \StringTok{"tiempo\_pantalla\_finde"}\NormalTok{,}
\NormalTok{]}\CommentTok{\#aqui descartamos "etiqueta\_de\_adiccion"}

\NormalTok{contador }\OperatorTok{=} \DecValTok{0}
\ControlFlowTok{for}\NormalTok{ col }\KeywordTok{in}\NormalTok{ num\_cols:}
\NormalTok{    plt.figure(figsize}\OperatorTok{=}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{3}\NormalTok{))}
\NormalTok{    sns.boxplot(}
\NormalTok{        data}\OperatorTok{=}\NormalTok{df\_clean,}
\NormalTok{        y}\OperatorTok{=}\NormalTok{col,}
\NormalTok{        color}\OperatorTok{=}\NormalTok{colores[contador],}
\NormalTok{    )}
\NormalTok{    contador }\OperatorTok{+=} \DecValTok{1}
\NormalTok{    plt.xlabel(}\StringTok{""}\NormalTok{)}
\NormalTok{    plt.ylabel(col)}
\NormalTok{    plt.tight\_layout()}
\NormalTok{    plt.show()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-2.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-3.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-4.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-5.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-6.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-7.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-8.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-18-output-9.pdf}}

\emph{La visualización de las variables numéricas (edad, tiempo en
pantalla, uso de apps, sueño, etc.) muestra en general una distribución
bastante homogénea y centrada. Salvo por ligeras asimetrías o atípicos
aislados en hábitos de uso intensivo (como notificaciones o
videojuegos), las observaciones representan comportamientos reales de
los usuarios y no errores de registro, por lo que se decide conservar
todas las variables completas para el análisis.}

Se calculan las medidas de tendencia central y dispersión de cada
variable numérica \autocite{walpole2012probabilidad}:

\begin{equation}\protect\phantomsection\label{eq-media}{
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i
}\end{equation}

\begin{equation}\protect\phantomsection\label{eq-mediana}{
\text{Mediana} =
\begin{cases}
x_{\left(\frac{n+1}{2}\right)} & \text{si } n \text{ es impar} \\[6pt]
\dfrac{x_{(n/2)} + x_{(n/2+1)}}{2} & \text{si } n \text{ es par}
\end{cases}
}\end{equation}

\begin{equation}\protect\phantomsection\label{eq-varianza}{
s^2 = \frac{1}{n-1}\sum_{i=1}^{n} (x_i - \bar{x})^2
}\end{equation}

\begin{equation}\protect\phantomsection\label{eq-desviacion}{
s = \sqrt{s^2} = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n} (x_i - \bar{x})^2}
}\end{equation}

\begin{equation}\protect\phantomsection\label{eq-cv}{
CV = \frac{s}{\bar{x}} \times 100\%
}\end{equation}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ i }\KeywordTok{in}\NormalTok{ num\_cols:}
\NormalTok{  display(df\_clean[i].describe())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
count    7500.000000
mean       26.568800
std         5.197108
min        18.000000
25%        22.000000
50%        27.000000
75%        31.000000
max        35.000000
Name: edad, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean        7.499912
std         2.609188
min         3.000000
25%         5.220000
50%         7.525000
75%         9.810000
max        12.000000
Name: horas_diarias_pantalla, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean        3.273484
std         1.585342
min         0.500000
25%         1.910000
50%         3.270000
75%         4.630000
max         6.000000
Name: horas_redes_sociales, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean        2.014183
std         1.146039
min         0.000000
25%         1.020000
50%         2.040000
75%         2.990000
max         4.000000
Name: horas_videojuegos, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean        3.242420
std         1.600765
min         0.500000
25%         1.850000
50%         3.230000
75%         4.640000
max         6.000000
Name: horas_trabajo/estudio, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean        6.737561
std         1.283605
min         4.500000
25%         5.630000
50%         6.720000
75%         7.840000
max         9.000000
Name: horas_sueño, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean      134.257333
std        66.586883
min        20.000000
25%        76.000000
50%       134.000000
75%       191.000000
max       250.000000
Name: notificaciones_por_dia, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean       97.832400
std        48.423349
min        15.000000
25%        55.000000
50%        98.000000
75%       140.000000
max       180.000000
Name: aperturas_apps_por_dia, dtype: float64
\end{verbatim}

\begin{verbatim}
count    7500.000000
mean        9.243827
std         2.718281
min         3.580000
25%         6.960000
50%         9.260000
75%        11.540000
max        14.880000
Name: tiempo_pantalla_finde, dtype: float64
\end{verbatim}

\emph{Al evaluar la relación entre la media y la mediana, la mayoría de
las variables muestran valores muy cercanos, lo que refleja
distribuciones mayoritariamente simétricas. En cuanto a la dispersión,
variables de conteo diario (como notificaciones\_por\_dia y
aperturas\_apps\_por\_dia) registran una desviación estándar mayor en
proporción a su escala en comparación con las variables en horas (como
horas\_sueño o horas\_trabajo/estudio), las cuales presentan mayor
estabilidad. Finalmente, las variables asociadas a hábitos intensivos
digitales son las que exhiben mayor variabilidad y presencia de valores
extremos.}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ i }\KeywordTok{in}\NormalTok{ cat\_cols:}
\NormalTok{  df\_clean[i].value\_counts(normalize}\OperatorTok{=}\VariableTok{True}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
genero
Male      0.340400
Other     0.331467
Female    0.328133
Name: proportion, dtype: float64
\end{verbatim}

\begin{verbatim}
nivel_estres
High      0.341333
Low       0.333733
Medium    0.324933
Name: proportion, dtype: float64
\end{verbatim}

\begin{verbatim}
impacto_academico/laboral
No     0.5004
Yes    0.4996
Name: proportion, dtype: float64
\end{verbatim}

\begin{verbatim}
estado_adiccion
Adicto       0.707733
No adicto    0.292267
Name: proportion, dtype: float64
\end{verbatim}

\emph{Las variables de género (Male: 34.0\%, Other: 33.1\%, Female:
32.8\%), nivel de estrés (High: 34.1\%, Low: 33.4\%, Medium: 32.5\%) e
impacto académico/laboral (No: 50.0\%, Yes: 50.0\%) presentan una
distribución completamente equitativa e uniforme, sin presencia de
categorías minoritarias que puedan sesgar el análisis. La única
excepción es estado\_adiccion, la cual exhibe un desbalance
significativo donde el 70.8\% corresponde a usuarios clasificados como
``Adicto'' y solo el 29.2\% a ``No adicto''. Por otro lado, la variable
nivel\_estres se tratará como ordinal debido a que sus categorías (Low,
Medium, High) poseen un orden jerárquico natural implícito.}

\subsection{Análisis multivariado}\label{anuxe1lisis-multivariado}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_num }\OperatorTok{=}\NormalTok{ df\_clean[num\_cols}\OperatorTok{+}\NormalTok{ [}\StringTok{"etiqueta\_de\_adiccion"}\NormalTok{]].copy()}
\CommentTok{\# 1. Primero va el tamaño y la resolución (el lienzo)}
\NormalTok{plt.figure(figsize}\OperatorTok{=}\NormalTok{(}\DecValTok{30}\NormalTok{, }\DecValTok{10}\NormalTok{), dpi}\OperatorTok{=}\DecValTok{300}\NormalTok{)}

\CommentTok{\# 2. Luego armamos el mapa de calor con tus mismos parámetros}
\NormalTok{sns.heatmap(}
\NormalTok{    df\_num.corr(),}
\NormalTok{    annot}\OperatorTok{=}\VariableTok{True}\NormalTok{,}
\NormalTok{    fmt}\OperatorTok{=}\StringTok{".1f"}\NormalTok{,}
\NormalTok{    vmax}\OperatorTok{=}\DecValTok{1}\NormalTok{,}
\NormalTok{    center}\OperatorTok{=}\DecValTok{0}\NormalTok{,}
\NormalTok{    linewidths}\OperatorTok{=}\FloatTok{0.5}\NormalTok{,  }\CommentTok{\# Líneas divisorias sutiles}
\NormalTok{    cbar\_kws}\OperatorTok{=}\NormalTok{\{}\StringTok{"shrink"}\NormalTok{: }\DecValTok{1}\NormalTok{\},  }\CommentTok{\# Barra de color un poco más chica}
\NormalTok{    annot\_kws}\OperatorTok{=}\NormalTok{\{}\StringTok{"size"}\NormalTok{: }\DecValTok{23}\NormalTok{\},  }\CommentTok{\# Números chiquitos para que no se amontonen}
\NormalTok{)}
\NormalTok{plt.xticks(fontsize}\OperatorTok{=}\DecValTok{29}\NormalTok{)   }\CommentTok{\# etiquetas del eje X más grandes}
\NormalTok{plt.yticks(fontsize}\OperatorTok{=}\DecValTok{29}\NormalTok{)   }\CommentTok{\# etiquetas del eje Y más grandes}
\CommentTok{\# 3. Ponemos el título y mostramos}
\NormalTok{plt.title(}\StringTok{"Matriz de Correlación de Variables Numéricas"}\NormalTok{)}
\NormalTok{plt.show()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-25-output-1.pdf}}

\emph{Instrucciones para esta sección: identificar en el mapa de calor
los pares de variables con correlación fuerte (positiva o negativa) y
comentar si sugieren colinealidad. Aclarar que la correlación no implica
causalidad.}

La correlación de Pearson mide la fuerza y dirección de la relación
lineal entre dos variables, y se calcula a partir de la covarianza y las
desviaciones estándar de cada una \autocite{walpole2012probabilidad}:

\begin{equation}\protect\phantomsection\label{eq-correlacion}{
r_{xy} = \frac{\text{cov}(x,y)}{s_x \, s_y}
}\end{equation}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{TODO}\CommentTok{: calcular y ordenar las correlaciones de cada variable numérica (num\_cols) con etiqueta\_de\_adiccion.}
\CommentTok{\#Chamba Jossep}
\end{Highlighting}
\end{Shaded}

\emph{Instrucciones para esta sección: comentar qué variables tienen
mayor asociación lineal con la etiqueta objetivo y cuáles tienen
asociación muy baja. Aclarar que esto es solo un indicio y no una
selección final de variables para el modelo.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{TODO}\CommentTok{: graficar boxplots comparativos de variables numéricas clave (por ejemplo, horas\_diarias\_pantalla, horas\_redes\_sociales, horas\_sueño) separadas por etiqueta\_de\_adiccion.}
\KeywordTok{del}\NormalTok{ plt}
\ImportTok{import}\NormalTok{ matplotlib.pyplot }\ImportTok{as}\NormalTok{ plt}
\NormalTok{sns.boxplot(data}\OperatorTok{=}\NormalTok{df\_clean, x}\OperatorTok{=}\StringTok{"estado\_adiccion"}\NormalTok{, y }\OperatorTok{=}\StringTok{"horas\_ocio"}\NormalTok{, palette }\OperatorTok{=} \StringTok{"husl"}\NormalTok{, legend}\OperatorTok{=}\VariableTok{True}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-27-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-28-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-29-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-30-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-31-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-32-output-1.pdf}}

\begin{verbatim}
['edad',
 'horas_diarias_pantalla',
 'horas_redes_sociales',
 'horas_videojuegos',
 'horas_trabajo/estudio',
 'horas_sueño',
 'notificaciones_por_dia',
 'aperturas_apps_por_dia',
 'tiempo_pantalla_finde']
\end{verbatim}

\begin{verbatim}
['genero', 'nivel_estres', 'impacto_academico/laboral']
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-35-output-1.pdf}}

\emph{Instrucciones para esta sección: comentar cómo cambian la
tendencia central y la dispersión de cada variable entre las dos clases,
y si hay solapamiento amplio entre grupos (lo que anticiparía dificultad
para separar las clases con un solo predictor).}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plt.figure(figsize}\OperatorTok{=}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{5}\NormalTok{))}
\NormalTok{sns.countplot(data}\OperatorTok{=}\NormalTok{df\_clean, x}\OperatorTok{=}\StringTok{"nivel\_estres"}\NormalTok{, hue}\OperatorTok{=}\StringTok{"estado\_adiccion"}\NormalTok{,}
\NormalTok{              order}\OperatorTok{=}\NormalTok{[}\StringTok{"Low"}\NormalTok{,}\StringTok{"Medium"}\NormalTok{,}\StringTok{"High"}\NormalTok{], palette}\OperatorTok{=}\StringTok{"colorblind"}\NormalTok{)}
\NormalTok{plt.title(}\StringTok{"Nivel de estrés, agrupado por estado de adicción"}\NormalTok{)}
\NormalTok{plt.xlabel(}\StringTok{"Nivel de estrés"}\NormalTok{)}
\NormalTok{plt.ylabel(}\StringTok{"Conteo"}\NormalTok{)}
\NormalTok{plt.tight\_layout()}
\NormalTok{plt.show()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-36-output-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{TODO}\CommentTok{: graficar histogramas o barras agrupadas comparando subgrupos (por ejemplo, nivel\_estres o impacto\_academico/laboral vs. etiqueta\_de\_adiccion).}
\ControlFlowTok{for}\NormalTok{ columna }\KeywordTok{in}\NormalTok{ cat\_cols:}
\NormalTok{  sns.histplot(data}\OperatorTok{=}\NormalTok{df\_clean,x }\OperatorTok{=}\NormalTok{ columna, hue }\OperatorTok{=} \StringTok{\textquotesingle{}etiqueta\_de\_adiccion\textquotesingle{}}\NormalTok{)}
\NormalTok{  plt.show()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-37-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-37-output-2.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-37-output-3.pdf}}

\emph{Instrucciones para esta sección: interpretar las proporciones (no
solo los conteos) entre subgrupos, evitando conclusiones que
estigmaticen a los usuarios. Comentar si estas variables parecen ser
causa, consecuencia o simplemente indicadores asociados al uso
problemático.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{TODO}\CommentTok{: graficar al menos 5 diagramas de dispersión (scatterplots) entre pares de variables numéricas (num\_cols), coloreando por etiqueta\_de\_adiccion.}

\NormalTok{sns.scatterplot(data}\OperatorTok{=}\NormalTok{df\_renombrado, x}\OperatorTok{=} \StringTok{\textquotesingle{}horas\_trabajo/estudio\textquotesingle{}}\NormalTok{, y}\OperatorTok{=} \StringTok{\textquotesingle{}horas\_diarias\_pantalla\textquotesingle{}}\NormalTok{, hue }\OperatorTok{=} \StringTok{\textquotesingle{}etiqueta\_de\_adiccion\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-38-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-39-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-40-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-41-output-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{Project-Report_files/figure-pdf/cell-42-output-1.pdf}}

\emph{Instrucciones para esta sección: para cada par de variables,
comentar si se observa un patrón (lineal o no lineal), agrupamientos, o
separación visible entre clases. Si los colores se solapan mucho,
señalar que esas dos variables por sí solas no bastan para separar las
clases.}

La covarianza mide cómo varían juntas dos variables: positiva si crecen
juntas, negativa si una crece cuando la otra decrece
\autocite{walpole2012probabilidad}.

\begin{equation}\protect\phantomsection\label{eq-covarianza}{
\text{cov}(x,y) = \frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y})
}\end{equation}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{TODO}\CommentTok{: calcular la covarianza entre pares de variables numéricas relevantes (num\_cols).}
\NormalTok{df\_number }\OperatorTok{=}\NormalTok{ df\_clean.select\_dtypes(include}\OperatorTok{=}\StringTok{\textquotesingle{}number\textquotesingle{}}\NormalTok{)}
\NormalTok{df\_number.corr()}
\end{Highlighting}
\end{Shaded}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}lllllllllllll@{}}
\toprule\noalign{}
& edad & horas\_diarias\_pantalla & horas\_redes\_sociales &
horas\_videojuegos & horas\_trabajo/estudio & horas\_sueño &
notificaciones\_por\_dia & aperturas\_apps\_por\_dia &
tiempo\_pantalla\_finde & etiqueta\_de\_adiccion & horas\_ocio &
ratio\_finde\_diario \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
edad & 1.000000 & 0.012767 & 0.000342 & -0.026107 & -0.017147 &
-0.007462 & 0.000387 & -0.002276 & 0.015286 & 0.004220 & -0.015024 &
0.002679 \\
horas\_diarias\_pantalla & 0.012767 & 1.000000 & 0.010321 & 0.001140 &
0.003108 & 0.019343 & 0.000811 & 0.024448 & 0.964295 & 0.577112 &
0.009036 & -0.632299 \\
horas\_redes\_sociales & 0.000342 & 0.010321 & 1.000000 & -0.000902 &
-0.002580 & 0.005947 & -0.008593 & -0.000371 & 0.011404 & 0.414244 &
0.810238 & -0.000316 \\
horas\_videojuegos & -0.026107 & 0.001140 & -0.000902 & 1.000000 &
0.004384 & -0.002874 & 0.015563 & -0.009917 & -0.006282 & 0.008485 &
0.585370 & -0.019130 \\
horas\_trabajo/estudio & -0.017147 & 0.003108 & -0.002580 & 0.004384 &
1.000000 & -0.027150 & -0.017518 & -0.021676 & 0.004667 & 0.001103 &
0.000478 & -0.007629 \\
horas\_sueño & -0.007462 & 0.019343 & 0.005947 & -0.002874 & -0.027150 &
1.000000 & 0.016273 & 0.005692 & 0.018933 & 0.035496 & 0.003137 &
-0.002452 \\
notificaciones\_por\_dia & 0.000387 & 0.000811 & -0.008593 & 0.015563 &
-0.017518 & 0.016273 & 1.000000 & 0.004598 & -0.002199 & -0.000660 &
0.002154 & -0.009572 \\
aperturas\_apps\_por\_dia & -0.002276 & 0.024448 & -0.000371 & -0.009917
& -0.021676 & 0.005692 & 0.004598 & 1.000000 & 0.021069 & 0.011041 &
-0.006113 & -0.023674 \\
tiempo\_pantalla\_finde & 0.015286 & 0.964295 & 0.011404 & -0.006282 &
0.004667 & 0.018933 & -0.002199 & 0.021069 & 1.000000 & 0.555426 &
0.005564 & -0.428720 \\
etiqueta\_de\_adiccion & 0.004220 & 0.577112 & 0.414244 & 0.008485 &
0.001103 & 0.035496 & -0.000660 & 0.011041 & 0.555426 & 1.000000 &
0.340828 & -0.363188 \\
horas\_ocio & -0.015024 & 0.009036 & 0.810238 & 0.585370 & 0.000478 &
0.003137 & 0.002154 & -0.006113 & 0.005564 & 0.340828 & 1.000000 &
-0.011468 \\
ratio\_finde\_diario & 0.002679 & -0.632299 & -0.000316 & -0.019130 &
-0.007629 & -0.002452 & -0.009572 & -0.023674 & -0.428720 & -0.363188 &
-0.011468 & 1.000000 \\
\end{longtable}
}

\emph{Instrucciones para esta sección: interpretar el signo de la
covarianza (si dos variables crecen o decrecen juntas) y explicar por
qué se complementa con la correlación (que sí permite comparar la fuerza
de la relación entre variables con escalas distintas).}

\section{Conclusiones de P1}\label{conclusiones-de-p1}

\emph{Instrucciones para esta sección: redactar entre 4 y 6 conclusiones
numeradas, basadas únicamente en los resultados obtenidos arriba (no
inventar cifras). Deben cubrir, como mínimo: (1) calidad de datos
(nulos, duplicados) y qué se hizo al respecto, (2) si la clase objetivo
está balanceada o no y qué implica para P2, (3) qué variables se
excluyen como predictoras y por qué, (4) qué variables lucen más
prometedoras para el modelamiento, y (5) qué se debe tener en cuenta al
pasar a la P2 (codificación, escalamiento, evaluación).}

\section{Limitaciones y consideraciones
éticas}\label{limitaciones-y-consideraciones-uxe9ticas}

El archivo no incluye documentación sobre el muestreo, instrumento de
medición, país, periodo de recolección ni procedimiento de etiquetado.
En consecuencia, la muestra no debe asumirse representativa de la
población universitaria peruana ni de un grupo demográfico específico.
Además, el término ``adicción'' debe tratarse como una etiqueta del
dataset y no como un diagnóstico clínico. La evidencia académica
recomienda emplear instrumentos validados y distinguir entre uso
frecuente y uso problemático \textcite{Kwon2013}; \textcite{Csibi2018}.

Si este análisis se trasladara a un contexto real, la privacidad, el
consentimiento informado y el riesgo de estigmatización serían
centrales. Una predicción debe apoyar la prevención o la derivación
voluntaria, nunca justificar sanciones automáticas o decisiones de alto
impacto.

\printbibliography[title=Referencias]

\end{document}
